# Configuração do Fly.io
app = "system32-delicate-snowflake-6693"
primary_region = "gru" # Use a região mais próxima

[build]

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80